"""UI tests for rich analysis display in clip details."""

import os
from pathlib import Path
from types import SimpleNamespace

import pytest

from models.cinematography import CinematographyAnalysis
from models.clip import Source
from tests.conftest import make_test_clip


@pytest.fixture
def qapp():
    os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")

    from PySide6.QtWidgets import QApplication

    app = QApplication.instance()
    if app is None:
        app = QApplication([])
    return app


@pytest.fixture
def source():
    return Source(
        id="src-1",
        file_path=Path("/test/video.mp4"),
        duration_seconds=10.0,
        fps=30.0,
        width=1280,
        height=720,
    )


def _rich_analysis() -> CinematographyAnalysis:
    return CinematographyAnalysis(
        shot_size="CU",
        shot_size_confidence=0.92,
        camera_angle="low_angle",
        angle_effect="power",
        camera_movement="pan",
        movement_direction="right",
        dutch_tilt="slight",
        camera_position="three_quarter",
        subject_position="left",
        headroom="tight",
        lead_room="negative",
        balance="asymmetrical",
        subject_count="group",
        subject_type="person",
        focus_type="shallow",
        background_type="blurred",
        estimated_lens_type="telephoto",
        lighting_style="dramatic",
        lighting_direction="side",
        light_quality="hard",
        color_temperature="warm",
        emotional_intensity="high",
        suggested_pacing="fast",
        analysis_model="gemini-test",
        analysis_mode="video",
    )


def test_clip_details_sidebar_shows_rich_analysis(qapp, source):
    from ui.clip_details_sidebar import ClipDetailsSidebar

    clip = make_test_clip("c1")
    clip.cinematography = _rich_analysis()

    sidebar = ClipDetailsSidebar()
    sidebar.video_player._setup_player = lambda: None
    sidebar.video_player._player_ready = True

    sidebar.show_clip(clip, source)
    qapp.processEvents()

    text = sidebar.cinematography_label.text()
    assert "Shot Size: CU (92%)" in text
    assert "Camera: Low Angle, Power, Three Quarter, Dutch Tilt: Slight" in text
    assert "Movement: Pan right" in text
    assert "Composition: Left, Tight, Negative, Asymmetrical" in text
    assert "Lighting: Dramatic, Side, Hard, Warm" in text
    assert sidebar.cinematography_meta_label.text() == "Generated by gemini-test · video mode"
    assert sidebar.cinematography_meta_label.isHidden() is False


def test_clip_details_sidebar_refreshes_rich_analysis(qapp, source):
    from ui.clip_details_sidebar import ClipDetailsSidebar

    clip = make_test_clip("c1")
    sidebar = ClipDetailsSidebar()
    sidebar.video_player._setup_player = lambda: None
    sidebar.video_player._player_ready = True

    sidebar.show_clip(clip, source)
    qapp.processEvents()
    assert sidebar.cinematography_label.text() == "Run Rich Analysis to analyze..."

    analysis = _rich_analysis()
    sidebar.refresh_cinematography_if_showing(clip.id, analysis)
    qapp.processEvents()

    assert clip.cinematography is analysis
    assert "Shot Size: CU (92%)" in sidebar.cinematography_label.text()


def test_cinematography_ready_refreshes_sidebar_rich_analysis():
    from ui.main_window import MainWindow

    clip = make_test_clip("c1")
    analysis = _rich_analysis()
    sidebar_calls = []
    shot_calls = []
    dirty_calls = []

    window = SimpleNamespace(
        clips_by_id={clip.id: clip},
        analyze_tab=SimpleNamespace(
            update_clip_cinematography=lambda clip_id, cinematography: None,
            update_clip_shot_type=lambda clip_id, shot_type: None,
        ),
        clip_details_sidebar=SimpleNamespace(
            refresh_shot_type_if_showing=lambda clip_id, shot_type: shot_calls.append(
                (clip_id, shot_type)
            ),
            refresh_cinematography_if_showing=lambda clip_id, cinematography: sidebar_calls.append(
                (clip_id, cinematography)
            ),
        ),
        _mark_dirty=lambda: dirty_calls.append(True),
    )

    MainWindow._on_cinematography_clip_ready(window, clip.id, analysis)

    assert clip.cinematography is analysis
    assert clip.shot_type == "close-up"
    assert shot_calls == [(clip.id, "close-up")]
    assert sidebar_calls == [(clip.id, analysis)]
    assert dirty_calls == [True]
